#
//  metrics.yml
//  
//
//  Created by Suhito Dita on 24/7/26.
//

name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:


permissions:
  contents: write


jobs:

  metrics:

    runs-on: ubuntu-latest

    steps:

      - uses: lowlighter/metrics@latest

        with:

          filename: github-metrics.svg

          token: ${{ secrets.METRICS_TOKEN }}

          user: ToTo1403


          template: classic


          base:
            header
            activity
            community
            repositories
            metadata


          config_timezone: Asia/Phnom_Penh


          plugin_languages: yes

          plugin_languages_limit: 10

          plugin_languages_sections:
            most-used
            recently-used


          plugin_isocalendar: yes


          plugin_habits: yes

          plugin_habits_days: 30


          plugin_lines: yes


          plugin_stars: yes


          plugin_achievements: yes


          plugin_topics: yes


          plugin_topics_limit: 20


          plugin_followup: yes


          plugin_people: yes


          plugin_people_limit: 10


          plugin_repositories: yes


          plugin_activity: yes
